### ISSUE TITLE
load.py won't run as is

### ISSUE THREAD

**Issue by badfun** [trek10inc/ddb-single-table-example#1]
Thanks for the article and example code. I found that I was unable to run load.py until I made the following changes:

- added ProvisionedThroughput to both main table and GSI definitions
- removed BillingMode entirely

Not sure why that was necessary as the code seems to follow the SDK documentation, but I could not get it to run without the changes.
I am using Python 3.7.0

**Comment by forrestbrazeal** [comment]
@badfun What version of boto were you using? Should work with the latest.

**Comment by ehemmerlin** [comment]
Good tutorial but same here with boto version: 2.49.0
I had to follow the steps given by @badfun to make it work
>     * added ProvisionedThroughput to both main table and GSI definitions
>     * removed BillingMode entirely

**Comment by badfun** [comment]
@forrestbrazeal 
Name: boto3
Version: 1.9.27

I installed it to follow your tutorial. Don't work with python normally.

**Comment by badfun** [comment]
@forrestbrazeal You are correct sir. I just updated to version 1.9.95 and reverted to the original code and it ran fine.
thank you.

**Comment by ehemmerlin** [comment]
@forrestbrazeal @badfun My mistake, it works indeed like a charm with boto3 version 1.9.95
